Website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('story1.urls')),
    path('tk1/',include('tk1.urls')),
    path('story7/',include('story7.urls')),
    path('story8/',include('story8.urls')),
    path('story9/',include('story9.urls')),
]

# path('sotry1/a',include('story1.urls'))

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('AcademicIsland/story1/', views.index, name='index'),
    path('AcademicIsland/story5/', views.matakuliahCreate, name='matakuliah'),

    path('',views.home, name="home"),
    path('ProfileIsland/',views.profile, name="profile"),
    path('AcademicIsland/',views.academic, name="academic"),
    path('AchievementIsland/',views.achievement, name="achievement"),
    path('CVIsland/',views.cv, name="cv"),
    path('IsolatedIsland/',views.isolated, name="isolated"),
    path('AcademicIsland/story5/MataKuliah', views.matakuliahShow, name='matakuliah'),
    path("AcademicIsland/story5/MataKuliah/<int:pk>", views.matakuliahDelete, name="matakuliahDelete"),
    path("AcademicIsland/story5/MataKuliah/no<int:pk>", views.matakuliahDetails, name="matakuliahDetails"),
    path("uts/", views.uts, name="uts"),
]

tk1/urls.py
from django.urls import path

from . import views

app_name = 'tk1'

urlpatterns = [
    path('',views.home, name="home"),
    path('perpu/',views.perpu, name="perpu"),
    path('uu/',views.uu, name="uu"),
    path('pp/',views.pp, name="pp"),
    path('perpres/',views.perpres, name="perpres"),
    path('perda/',views.perda, name="perda"),
    path('pergub/',views.pergub, name="pergub"),

]

story1/models.py
from django.db import models

# Create your models here.

class ShowMatkul(models.Model):
    Nama_Mata_Kuliah        = models.CharField(max_length=50)
    Dosen_Pengajar          = models.CharField(max_length=50)
    Jumlah_SKS              = models.CharField(max_length=50)
    Deskripsi_Mata_Kuliah   = models.CharField(max_length=50)
    Semester_Tahun          = models.CharField(max_length=50)
    Ruang_Kelas             = models.CharField(max_length=50)

    def __str__(self):
        return "{}. {}".format(self.id , self.Nama_Mata_Kuliah)

story1/forms.py
from django import forms


class MataKuliah(forms.Form):
    Nama_Mata_Kuliah        = forms.CharField()
    Dosen_Pengajar          = forms.CharField()
    Jumlah_SKS              = forms.CharField()
    Deskripsi_Mata_Kuliah   = forms.CharField()
    Semester_Tahun          = forms.CharField()
    Ruang_Kelas             = forms.CharField()

story1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

#Import from
from .forms import MataKuliah
from .models import ShowMatkul
# Create your views here.

def index(request):
    return render(request, 'story1.html')

def home(request):
    return render(request,'homepage.html')

def profile(request):
    return render(request, 'profileisland.html')

def academic(request):
    return render(request, 'academicisland.html')

def achievement(request):
    return render(request, 'achievementisland.html')

def cv(request):
    return render(request, 'cvisland.html')

def isolated(request):
    return render(request, 'isolatedisland.html')

def matakuliahCreate(request):
    Mata_Kuliah = MataKuliah()

    if request.method == 'POST':
        ShowMatkul.objects.create(
            Nama_Mata_Kuliah        = request.POST['Nama_Mata_Kuliah'],
            Dosen_Pengajar          = request.POST['Dosen_Pengajar'],
            Jumlah_SKS              = request.POST['Jumlah_SKS'],
            Deskripsi_Mata_Kuliah   = request.POST['Deskripsi_Mata_Kuliah'],
            Semester_Tahun          = request.POST['Semester_Tahun'],
            Ruang_Kelas             = request.POST['Ruang_Kelas'],
        )

        return HttpResponseRedirect("/AcademicIsland/story5/MataKuliah")

    context = {
        'MataKuliah':Mata_Kuliah
    }
    
    return render(request, 'matakuliahCreate.html',context)

def matakuliahShow(request):
    Matkul = ShowMatkul.objects.all()
    context = {
        'MataKuliah':'Mata Kuliah',
        'Matkul': Matkul
    }
    if request.method == 'POST':
        print("apakah berhasil")
    return render(request, 'matakuliahShow.html',context)

def matakuliahDelete(request,pk):
    deleteMatkul = ShowMatkul.objects.filter(pk=pk)
    deleteMatkul.delete()

    return HttpResponseRedirect("/AcademicIsland/story5/MataKuliah")

def matakuliahDetails(request,pk):
    detailsMatkul = ShowMatkul.objects.get(pk=pk)
    context = {
        'list' : detailsMatkul
    }

    return render(request, 'matakuliahDetails.html',context)


def uts(request):
    return render(request,'nyoba.html')

story1/templates/academicisland.html
<!DOCTYPE html>
<html lang="en">

    {% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Academic</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Caesar Dressing' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
    crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'home/style.css' %}">
</head>
<body>
    {% include "navbar.html" %}
    <div id="welcome">
        <div class="row" id="welcome_profile">
            <div class="col-xs-4 row-grid" id="isi">
                <h1>IT LOOKS LIKE<br>YOU ARRIVED SAFELY.</h1>
            </div>
        </div>
    </div>

    <section id ="isi_homepage">
        <div class="row">
            <div class="col-xs-6 col-md-6 col-sm-6">
                <a href="/">
                    <img src=" {% static 'img/AcademicIsland.png' %}">
                </a>
            </div>
            <div class="col-xs-6 col-md-6 col-sm-6" id="isi_homepage_tulisan">
                <h3>ACADEMIC ISLAND</h3>
            </div>
        </div>

        <div id="isi_profile">
            <h3>Welcome in Academic Island!!<br>
                On this island, you will find several works by Skyhaf.<br>
                Not only that, you can edit some of courses.<br>
                feel free if you want to take a look..
            </h3>
            <div id="spasi_homepage"></div>
            <div id="table1">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Mata Kuliah</th>
                            <th scope="col">Nama Tugas</th>
                            <th scope="col">Link</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>PPW</td>
                            <td>Story 1</td>
                            <td><a href="story1/" target="_blank">Click Here</a>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>PPW</td>
                            <td>Story 2</td>
                            <td><a href="https://www.figma.com/file/QTd3DCikKNXPRkk9XF3AzY/Wireframe-%26-Prototype?node-id=0%3A1" target="_blank">
                                Click Here</a>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>PPW</td>
                            <td>Story 5</td>
                            <td><a href="story5/" target="_blank">Click Here</a>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>PPW</td>
                            <td>Story 7</td>
                            <td><a href="/story7" target="_blank">Click Here</a>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>PPW</td>
                            <td>Story 8</td>
                            <td><a href="/story8" target="_blank">Click Here</a>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>PPW</td>
                            <td>Story 9</td>
                            <td><a href="/story9" target="_blank">Click Here</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <!-- <div>
                <form method="POST">
                    {% csrf_token %}
                    <table>
                        {{ MataKuliah.as_table }}
                    </table>
                    <button type="submit"> SUBMIT </button>
                </form>
            </div> -->
        </div>
</section>

    <div>
        <div id="back_button">
            <a href="/"><img src=" {% static 'img/back_button.png' %}"></a>
        </div>
        {% include "footer.html" %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

story1/templates/achievementisland.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Achievement</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Caesar Dressing' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
    crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'home/style.css' %}">
</head>
<body>
    {% include "navbar.html" %}
    <div style="margin-bottom: 1000px;">
        <h2>Achievement Island</h2>
        <p>Under construction..</p>
    </div>
    <div>
        <div id="back_button">
            <a href="/"><img src=" {% static 'img/back_button.png' %}"></a>
        </div>
        {% include "footer.html" %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

story1/templates/cvisland.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CV</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Caesar Dressing' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
    crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'home/style.css' %}">
</head>
<body>
    {% include "navbar.html" %}
    <div style="margin-bottom: 1000px;">
        <h2>CV Island</h2>
        <p>Under construction..</p>
    </div>
    <div>
        <div id="back_button">
            <a href="/"><img src=" {% static 'img/back_button.png' %}"></a>
        </div>
        {% include "footer.html" %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

story1/templates/footer.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <div class="row" id="footer">
        <div class="col-xs-4 row-grid">
            <div id="Social_Media">
                <a href="https://www.instagram.com/skyhaf/" target="_blank">
                    <img src=" {% static 'img/Instagram.png' %}">
                </a>
                <a href="https://www.linkedin.com/in/hafizbhadrikaalamsyah/" target="_blank">
                    <img src=" {% static 'img/LinkedIN_black.png' %}">
                </a>
                <a href="https://medium.com/@hafiznasution2002" target="_balnk">
                    <img src=" {% static 'img/medium.png' %}">
                </a>
            </div>
        </div>
        <div class="col-xs-4 row-grid" id="email_saya">
            Email : hafiznasution2002@gmail.com
        </div>
        <div class="col-xs-4 row-grid" id="for_fun">
            wanna go extreme?
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

story1/templates/homepage.html
<!DOCTYPE html>
<html lang="en">

    {% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/static/img/Perahu.png">
    <title>Hafiz Bhadrika Alamsyah</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Caesar Dressing' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
    crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'home/style.css' %}">
</head>
<body>
    {% include "navbar.html" %}
      
    <section id="welcome" >
        <br><br><br><br>
        <h1 id="alola">ALOLA!</h1>
        <br>    
        <p id="alola_">Hello adventurers, welcome to the world of skyhaf</p>
        <p>To explore, just tap the island.</p>
    </section>
    
    <section id ="isi_homepage">
        <div class="row" id="">
            <div class="col-xs-6 col-md-6 col-sm-6">
                <a href="ProfileIsland/">
                    <img src=" {% static 'img/ProfileIsland.png' %}">
                </a>
            </div>
            <div class="col-xs-6 col-md-6 col-sm-6" id="isi_homepage_tulisan">
                <h3>PROFILE ISLAND</h3>
                <p>
                    Apparently, this island provides various information about skyhaf.<br>
                    
                    Let's find out!
                </p>
            </div>
        </div>
        <div id="spasi_homepage"></div>
        <div class="row">
            <div class="col-xs-6 col-md-6 col-sm-6" id="isi_homepage_tulisan">
                <h3>ACADEMIC ISLAND</h3>
                <p>
                    Paper? Code? Deadline? What is that?<br>
                    Hmmm judging from the name of the island,<br> 
                    it's not that far off with tasks ... 
                    But, let's explore!
                </p>
            </div>
            <div class="col-xs-6 col-md-6 col-sm-6">
                <a href="AcademicIsland">
                    <img src=" {% static 'img/AcademicIsland.png' %}">
                </a>
            </div>
        </div>
        <div id="spasi_homepage">
        </div>
        <div class="row">
            <div class="col-xs-6 col-md-6 col-sm-6">
                <a href="AchievementIsland">
                    <img src=" {% static 'img/AchievementIsland.png' %}">
                </a>
            </div>
            <div class="col-xs-6 col-md-6 col-sm-6" id="isi_homepage_tulisan">
                <h3>ACHIEVEMENT ISLAND</h3>
                <p>
                    Wowww, take a look at this island.<br>
                    There are tons of chests to see.<br>
                    What do you think about the contents of the chest? <br>
                    Shall we go in and find out?
                </p>
            </div>
        </div>
        <div id="spasi_homepage">
        </div>
        <div class="row">
            <div class="col-xs-6 col-md-6 col-sm-6" id="isi_homepage_tulisan">
                <h3>CV ISLAND</h3>
                <p>
                    Looks like this island contains pretty serious stuff ... <br>
                    Let's take a look!
                </p>
            </div>
            <div class="col-xs-6 col-md-6 col-sm-6">
                <a href="CVIsland">
                    <img src=" {% static 'img/CVIsland.png' %}">
                </a>
            </div>
        </div>
        <div id="spasi_homepage">
        </div>
        <div class="row">
            <div class="col-xs-6 col-md-6 col-sm-6">
                <a href="IsolatedIsland">
                    <img src=" {% static 'img/IsolatedIsland.png' %}">
                </a>
            </div>
            <div class="col-xs-6 col-md-6 col-sm-6" id="isi_homepage_tulisan">
                <h3>ISOLATED ISLAND</h3>
                <p>
                    Why is this island isolated? are there pirates?<br>
                    monster? or other mysterious things?<br>
                    Do you want to explore this island?
                </p>
            </div>
        </div>

    </section>

    {% include "footer.html" %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

story1/templates/matakuliahShow.html
<!DOCTYPE html>
<html lang="en">

    {% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Academic</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Caesar Dressing' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
    crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'home/style.css' %}">
</head>
<body>
    {% include "navbar.html" %}
    <div id="welcome">
        <div class="row" id="welcome_profile">
            <div class="col-xs-4 row-grid" id="isi">
                <h1>IT LOOKS LIKE<br>YOU ARRIVED SAFELY.</h1>
            </div>
        </div>
    </div>

    <section id ="isi_homepage">
        <div class="row">
            <div class="col-xs-6 col-md-6 col-sm-6">
                <a href="/">
                    <img src=" {% static 'img/AcademicIsland.png' %}">
                </a>
            </div>
            <div class="col-xs-6 col-md-6 col-sm-6" id="isi_homepage_tulisan">
                <h3>ACADEMIC ISLAND</h3>
            </div>
        </div>

        <div id="isi_profile">
            <h3>Here are the list of courses.<br>

            </h3>
            <div id="spasi_homepage"></div>
            <div>
                

                <table class="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">Nomor</th>
                        <th scope="col">Nama matkul jing</th>
                        <th scope="col">Dosennya tot</th>
                        <th scope="col">Jumlah Sksnya mek</th>
                        <th scope="col">semesternya COKK</th>
                        <th scope="col">Ruang KELASNYA MEK</th>
                        <th scope="col">Detailsnya bgst</th>
                        <th scope="col">udah hapus aje matkulnya tot</th>
                      </tr>
                    </thead>
                    {% for i in Matkul %}
                    <tbody>
                      <tr>
                        <th scope="row"> {{ forloop.counter }} </th>
                        <td>{{i.Nama_Mata_Kuliah}}</td>
                        <td>{{i.Dosen_Pengajar}}</td>
                        <td>{{i.Jumlah_SKS}}</td>
                        <td>{{i.Semester_Tahun}}</td>
                        <td>{{i.Ruang_Kelas}}</td>
                        <td><button><a href="{% url 'story1:matakuliahDetails' pk=i.pk %}"> Details </a></button></td>
                        <td><button><a href="{% url 'story1:matakuliahDelete' pk=i.pk %}" > Delete </a></button></td>
                      </tr>
                    </tbody>
                    {% endfor %}
                  </table>
                
                <!-- <form method="POST">
                    {% csrf_token %}
                    <table>
                        {{ MataKuliah.as_table }}
                    </table>
                </form> -->
            </div>
        </div>
</section>

    <div>
        <div id="back_button">
            <a href="/"><img src=" {% static 'img/back_button.png' %}"></a>
        </div>
        {% include "footer.html" %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

story1/templates/nyoba.html
<html>

{% load static %}
<head>
  <title>Pearl Necklace</title>
  <link href="{% static 'home/product.css' %}" rel="stylesheet" />

  <style>
      .par{
          color: red;
          background: yellow;
      }
      #par1{
          color:navy;
          background: aqua;
      }

  </style>
    <!-- <link href="{% static 'home/product.css' %}" rel="stylesheet" /> -->

</head>
<body>
<div id = "par1" style="color:blue">
Daftar Matklt:

</div>
<ul>
    <li>asd</li>
    <li>asasd</li>
    <li>fdfno</li>
    <li>egfhg</li>

</ul>


</body>
</html>