Website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('story1.urls')),
    path('tk1/',include('tk1.urls')),
    path('story7/',include('story7.urls')),
    path('story8/',include('story8.urls')),
    path('story9/',include('story9.urls')),
]

# path('sotry1/a',include('story1.urls'))

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.loginpage, name='login'),
    path('register/', views.register, name='register'),
    path('hello/', views.message, name='message'),
    path('logout/', views.logoutpage, name='logout')
]

tk1/urls.py
from django.urls import path

from . import views

app_name = 'tk1'

urlpatterns = [
    path('',views.home, name="home"),
    path('perpu/',views.perpu, name="perpu"),
    path('uu/',views.uu, name="uu"),
    path('pp/',views.pp, name="pp"),
    path('perpres/',views.perpres, name="perpres"),
    path('perda/',views.perda, name="perda"),
    path('pergub/',views.pergub, name="pergub"),

]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields= ['username', 'email', 'password1', 'password2']

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def loginpage(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/story9/hello')

    return render(request,'login.html')

def register(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/story9/')
    context = {'form' : form}
    return render(request,'register.html', context)

def message(request):
    if request.user.is_authenticated:
        return render(request,'hello.html')
    else:
        return redirect('/story9/')

def logoutpage(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('/story9/')
    else:
        return redirect('www.google.com/login dulu ya..')

story9/templates/hello.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Welcome Page</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Cabin:400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:900" rel="stylesheet">

    <link href='https://fonts.googleapis.com/css?family=Caesar Dressing' rel='stylesheet'>
    <link type="text/css" rel="stylesheet" href="{% static '/home/story9.css' %}">
	<!-- Custom stlylesheet -->
	<!-- <link type="text/css" rel="stylesheet" href="{% static 'css/stylex.css' %}" /> -->
</head>

<body>
	<a href="{% url 'story9:logout' %}">LOGOUT</a>
	<h1>Welcome {{ request.user }}</h1>
	<h1>{{ request.user.first_name }}</h1>
	<h1>{{ request.user.last_name }}</h1>
	<!-- <div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h3>Welcome To The Club</h3>
				<h1><span>{{ request.user.first_name }}</span></h1>
			</div>
			<h2>Hope You Enjoy</h2>
		</div>
    </div> -->

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

story9/templates/login.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Story 9</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!--Jquery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

	<link href='https://fonts.googleapis.com/css?family=Caesar Dressing' rel='stylesheet'>
	<link href='https://fonts.googleapis.com/css?family=Caesar Dressing' rel='stylesheet'>
    <link type="text/css" rel="stylesheet" href="{% static '/home/story9.css' %}">

</head>


<body>

    <h1> STORY 9 PPW </h1>
	<br>
    <!-- <img class="wave" src="{% static 'img/wave.svg' %}"> -->
	<div class="container">
		<!-- <div class="img">
			<img src="{% static 'img/celeb.svg' %}">
		</div> -->
		<div class="login-content">
			<form action="" method="POST">
                {% csrf_token %}
				<!-- <img src="{% static 'img/avatar.svg' %}"> -->
				<h2 class="title">Log In</h2>
           		<div class="input-div one">
           		   <!-- <div class="i">
           		   		<i class="fas fa-user"></i>
           		   </div> -->
           		   <div class="div">
           		   		<h5>Username</h5>
           		   		<input type="text" name="username">
           		   </div>
           		</div>
           		<div class="input-div pass">
           		   <!-- <div class="i"> 
           		    	<i class="fas fa-envelope"></i>
           		   </div> -->
           		   <div class="div">
           		    	<h5>Password</h5>
           		    	<input type="password" name="password">
            	   </div>
            	</div>
                {{ form.errors }}
                <a href="{% url 'story9:register' %}" id="signup">Sign Up Now</a>
            	<input type="submit" class="btn" value="Log In" id="login">
            </form>
        </div>
    </div>



    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="/static/home/styling8.js" type="text/javascript"></script>
</body>



</html>

story9/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link href='https://fonts.googleapis.com/css?family=Caesar Dressing' rel='stylesheet'>
    <link type="text/css" rel="stylesheet" href="{% static '/home/story9.css' %}">
</head>
<body>
    <!-- <img class="wave" src="{% static 'img/wave.svg' %}"> -->
	<div class="container">
		<!-- <div class="img">
			<!-- <img src="{% static 'img/bg.svg' %}"> -->
		</div> -->
		<div class="login-content">
			<form action="" method="POST">
                {% csrf_token %}
				<!-- <img src="{% static 'img/avatar.svg' %}"> -->
				<h2 class="title">Register</h2>
           		<div class="input-div one">
           		   <div class="i">
           		   		<i class="fas fa-user"></i>
           		   </div>
           		   <div class="div">
           		   		<h5>Username</h5>
           		   		{{ form.username }}
           		   </div>
           		</div>
           		<div class="input-div pass">
           		   <div class="i"> 
           		    	<i class="fas fa-envelope"></i>
           		   </div>
           		   <div class="div">
           		    	<h5>Email</h5>
           		    	{{ form.email }}
            	   </div>
            	</div>
            	<div class="input-div pass">
                    <div class="i"> 
                         <i class="fas fa-lock"></i>
                    </div>
                    <div class="div">
                        <h5>Password</h5>
                        {{ form.password1 }}
                    </div>
                </div>
                <div class="input-div pass">
                    <div class="i"> 
                         <i class="fas fa-lock"></i>
                    </div>
                    <div class="div">
                        <h5>Confirm Your Password</h5>
                        {{ form.password2 }}
                    </div>
                </div>
                {{ form.errors }}
                <a href="{% url 'story9:login' %}" id="signin">Already have an account?</a>
            	<input type="submit" class="btn" value="Sign Up">
            </form>
        </div>
    </div>

</body>
</html>